Eslint setup
rruidiaz/psl-workshop-api-testing-js pull request #6
Opened 2017-09-24 22:25 UTC by rruidiaz

2017-09-24 22:46 UTC, aperdomob requested changes

2017-09-24 22:46 UTC, aperdomob commented on test/MyFirstApiConsume.test.js
> -        expect(response.body).to.be.empty;
en vez de borrarlo puedes hacerlo con un assert
```
const { expect, assert } = chai;

assert.isEmpty(response.body)
```

2017-09-25 13:57 UTC, jhenaoz submitted a review, later dismissed
mismos comentarios que alejandro

2017-09-25 22:25 UTC, rruidiaz reviewed
Corregido!

2017-09-25 22:25 UTC, rruidiaz commented on test/MyFirstApiConsume.test.js
> -        expect(response.body).to.be.empty;
Corregido!

2017-09-25 22:31 UTC, aperdomob approved these changes

2017-09-25 22:43 UTC, merged